language: node_js

services:
  - docker

install:
  - echo "nothing needs to be installed"

before_script:
  - echo "no tests"

script:
  # Build
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-frontend ./udagram-frontend
  - docker build -t reverseproxy ./udagram-reverseproxy

  # Tagging
  - docker tag udagram-api-user eisel98/udagram-api-user:v1
  - docker tag udagram-api-feed eisel98/udagram-api-feed:v1
  - docker tag udagram-frontend eisel98/udagram-frontend:v1
  - docker tag reverseproxy eisel98/reverseproxy:v1

after_success: 
  # Push
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push eisel98/udagram-api-feed:v1
  - docker push eisel98/udagram-api-user:v1
  - docker push eisel98/udagram-frontend:v1
  - docker push eisel98/reverseproxy:v1



